export enum ActionType {
  FETCH_TOP_CITIES_WEATHER_LOADING = 'FETCH_TOP_CITIES_WEATHER_LOADING',
  FETCH_TOP_CITIES_WEATHER_SUCCESS = 'FETCH_TOP_CITIES_WEATHER_SUCCESS',
  FETCH_TOP_CITIES_WEATHER_FAIL = 'FETCH_TOP_CITIES_WEATHER_FAIL',
  REMOVE_TOP_CITY = 'REMOVE_TOP_CITY',
  ADD_FAVORITE_CITY = 'ADD_FAVORITE_CITY',
  REMOVE_FAVORITE_CITY = 'REMOVE_FAVORITE_CITY',
  DISMISS_FETCH_TOP_CITIES_WEATHER_ERROR = 'DISMISS_FETCH_TOP_CITIES_WEATHER_ERROR',

  SEARCH_CITY_LOADING = 'SEARCH_CITY_LOADING',
  SEARCH_CITY_SUCCESS = 'SEARCH_CITY_SUCCESS',
  SEARCH_CITY_FAIL = 'SEARCH_CITY_FAIL',
  RESET_SEARCH_CITY = 'RESET_SEARCH_CITY',

  FETCH_CITY_WEATHER_LOADING = 'FETCH_CITY_WEATHER_LOADING',
  FETCH_CITY_WEATHER_SUCCESS = 'FETCH_CITY_WEATHER_SUCCESS',
  FETCH_CITY_WEATHER_FAIL = 'FETCH_CITY_WEATHER_FAIL',
  DISMISS_FETCH_CITY_WEATHER_ERROR = 'DISMISS_FETCH_CITY_WEATHER_ERROR',

  EDIT_NOTE = 'EDIT_NOTE',
  ADD_NOTE = 'ADD_NOTE',
  DELETE_NOTE = 'DELETE_NOTE',
}
