export enum ActionType {
  FETCH_TOP_CITIES_WEATHER_LOADING = 'FETCH_TOP_CITIES_WEATHER_LOADING',
  FETCH_TOP_CITIES_WEATHER_SUCCESS = 'FETCH_TOP_CITIES_WEATHER_SUCCESS',
  FETCH_TOP_CITIES_WEATHER_FAIL = 'FETCH_TOP_CITIES_WEATHER_FAIL',
  REMOVE_TOP_CITY = 'REMOVE_TOP_CITY',

  FETCH_FAVORITE_CITIES = 'FETCH_FAVORITE_CITIES',
  ADD_FAVORITE_CITY = 'ADD_FAVORITE_CITY',
  REMOVE_FAVORITE_CITY = 'REMOVE_FAVORITE_CITY',

  SEARCH_CITY_LOADING = 'SEARCH_CITY_LOADING',
  SEARCH_CITY_SUCCESS = 'SEARCH_CITY_SUCCESS',
  SEARCH_CITY_FAIL = 'SEARCH_CITY_FAIL',

  FETCH_CITY_WEATHER_LOADING = 'FETCH_CITY_WEATHER_LOADING',
  FETCH_CITY_WEATHER_SUCCESS = 'FETCH_CITY_WEATHER_SUCCESS',
  FETCH_CITY_WEATHER_FAIL = 'FETCH_CITY_WEATHER_FAIL',

  FETCH_NOTES = 'FETCH_NOTES',
  EDIT_NOTE = 'EDIT_NOTE',
  ADD_NOTE = 'ADD_NOTE',
  DELETE_NOTE = 'DELETE_NOTE',
}
